### ISSUE TITLE
IntegrationXv30中流明晶石及其原礦的地圖ID錯誤

### ISSUE THREAD

**Issue by Lincutt** [Xcating/Json_Integration#4]
該ID正確應為6 (層岩巨淵:地下礦區)
但卻誤植為3 (提瓦特)

**Comment by Xcating** [comment]
抱歉，如果Bkebi不继续更新3.6版本的原神淫爬，我将不会支持bkebi格式的文件，你可以先使用Acrepi/Akebi进行传送

**Comment by Xcating** [comment]
抱歉，如果Bkebi不继续更新3.6版本的原神淫爬，我将不会支持bkebi格式的文件，你可以先使用Acrepi/Akebi进行传送
