### ISSUE TITLE
English translate

### ISSUE THREAD

**Issue by Xcating** [Xcating/Json_Integration#7]
English translate
1.Do not machine flip
2.Thanks You

**Comment by Xcating** [comment]
if you have time, you can help me translate these

**Comment by rathnesh12** [comment]
hi i think i can spend some time on translating

**Comment by Xcating** [comment]
@Dry1ceD7 Once translated, you can create a **pull request**

**Comment by Xcating** [comment]
Note: that it is the PR for the **_dev branch_**
